---
version: 3

dependencies:
  galaxy:
    collections:
      - name: amazon.aws
        version: 7.4.0
      - name: community.aws
        version: 7.1.0
      - name: cloud.terraform
        version: 2.0.0
      - name: kubernetes.core
        version: 3.0.1
      - name: community.general
  python:
    - botocore>=1.29.0
    - boto3>=1.26.0
    - kubernetes>=24.2.0
    - requests-oauthlib
    - jsonpatch
  system:
    - terraform
    - unzip
  ansible_core:
    package_pip: ansible-core==2.16.4
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  python_interpreter:
    package_system: "python3.11"
    python_path: "/usr/bin/python3.11"

images:
  base_image:
    name: registry-proxy.engineering.redhat.com/rh-osbs/ansible-automation-platform-25-ee-supported-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  append_base: |
    RUN echo "Target architecture is: $TARGETARCH"

    # Configure Terraform Repo
    RUN curl -o /etc/yum.repos.d/hashicorp.repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

  append_final: |
    # Use Python 3.11 as default
    RUN rm -f /bin/python3
    RUN ln -s /bin/python3.11 /bin/python3

    # Output collections list for debugging
    RUN ansible-galaxy collection list

    # Display terraform version
    RUN terraform version

    # Display kubectl version
    RUN kubectl version --client=true
